// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmcQ7O36xHermFiAKIAA_Bd4RwTRjQOvY',
    appId: '1:160343627791:web:4251b1c46a5b22ea4c2b7a',
    messagingSenderId: '160343627791',
    projectId: 'inteligencia-agro',
    authDomain: 'inteligencia-agro.firebaseapp.com',
    storageBucket: 'inteligencia-agro.firebasestorage.app',
    measurementId: 'G-085RMCCE1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDefWmSptDDOstLGhFjBEKy30hYT_2LycY',
    appId: '1:160343627791:android:dbf45f563b2dbd4b4c2b7a',
    messagingSenderId: '160343627791',
    projectId: 'inteligencia-agro',
    storageBucket: 'inteligencia-agro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPH4znVQe7-aSx862jS3RLQrM7arI9l4s',
    appId: '1:160343627791:ios:1c325c879f6ed3b94c2b7a',
    messagingSenderId: '160343627791',
    projectId: 'inteligencia-agro',
    storageBucket: 'inteligencia-agro.firebasestorage.app',
    iosBundleId: 'com.example.inteligenciaAgro',
  );

}